# Generated by Django 3.0 on 2020-04-16 12:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_areamodel_citymodel_restauranttypemodel_statemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttypemodel',
            name='area',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='admin_module.AreaModel'),
            preserve_default=False,
        ),
    ]
