# Generated by Django 3.0 on 2020-04-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_restauranttypemodel_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areamodel',
            name='area_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
