# Generated by Django 3.0 on 2020-04-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0005_auto_20200416_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restauranttypemodel',
            old_name='no',
            new_name='type_no',
        ),
    ]
